name: Cypress Tests

on:   
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        run: npx cypress run
        with:
          start: npm run start