name: Cypress Tests

on:   
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Frontend Repository
        uses: actions/checkout@v4
        with:
            path: 'frontend'

      - name: Checkout Backend Repository
        uses: actions/checkout@v4
        with:
            repository: 'cartistry416/cartistry-express'
            token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
            path: 'backend'

      - name: Install and start backend server
        run: |
            cd backend 
            npm install
            npm run build
            npm run start &
            sleep 5
            npx wait-on http://localhost:4000
        env:
            MONGODB_URI: ${{ secrets.MONGODB_URI }}
            JWT_SECRET: ${{ secrets.JWT_SECRET }}
            FRONTEND_URL: ${{ secrets.FRONTEND_URL }}

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
            working-directory: frontend
            start: npm start
            browser: chrome
            wait-on: http://localhost:3000/,http://localhost:4000/
            wait-on-timeout: 180

  deploy:
    needs: cypress-run
    runs-on: ubuntu-latest
    steps:
    - name: deploy
      run: |
          URL="${{ secrets.AMPLIFY_URL }}"
          curl -X POST -d {} "$URL" -H "Content-Type: application/json"